"""adding _created

Revision ID: 038d621760aa
Revises: fbbf9afd98fe
Create Date: 2023-08-28 22:32:42.800837

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '038d621760aa'
down_revision: Union[str, None] = 'fbbf9afd98fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created')
    # ### end Alembic commands ###
