@server=http://localhost:8000
@toker=Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZXJtYW5vQGdtYWlsLmNvbSIsImV4cCI6MTY5MzI3Mjk4OX0.WcDxrJVGCTAWVkzpYPMsacxQP9tYcWBcyp9MupjVz2Q"


###
GET {{server}}/v1/users

###
POST {{server}}/users
Content-Type: application/json

{
    "username": "John Doe",
    "email": "germano@gmail.com",
    "password": "1234"
}


###
POST {{server}}/auth/token
Content-Type: application/x-www-form-urlencoded
Accept-Content-Type: application/json

{
    "username": "germano@gmail.com",
    "password": "1234"
}