@server=http://localhost:8000

###
GET {{server}}/users

###
POST {{server}}/users
Content-Type: application/json

{
    "username": "John Doe",
    "email": "germano@gmail.com",
    "password": "1234"
}


###
POST {{server}}/token
Content-Type: application/x-www-form-urlencoded
Accept-Content-Type: application/json

{
    "username": "germano@gmail.com",
    "password": "1234"
}